DROP PROCEDURE P3.CUST_CRT;
DROP PROCEDURE P3.CUST_LOGIN;
DROP PROCEDURE P3.ACCT_OPN;
DROP PROCEDURE P3.ACCT_CLS;
DROP PROCEDURE P3.ACCT_DEP;
DROP PROCEDURE P3.ACCT_WTH;
DROP PROCEDURE P3.ACCT_TRX;
DROP PROCEDURE P3.ADD_INTEREST;
